### ISSUE TITLE
cal-schedule and a few others

### ISSUE THREAD

**Issue by lambdaloop** [berkeleyOSS/other-projects#2]
I'd like to suggest my open source Cal planner website:
https://github.com/lambdaloop/cal-schedule

There's also the js-scheme-stk scheme interpreter that I built (and was used for CS61AS for a bit):
https://github.com/lambdaloop/js-scheme-stk

Also, if you're okay with small projects, there's this script using simulated annealing to scheduling lab assistants:
https://github.com/lambdaloop/scheduling

**Comment by jpdstan** [comment]
thanks so much!! adding these to the list.
